// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bgzsjhuuqepkehkelpxh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJnenNqaHV1cWVwa2Voa2VscHhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ5MTgzMTYsImV4cCI6MjA5MDQ5NDMxNn0.fsGUWobLYETF0njhIb3DbRx3tlglT9HmbE83fv83KFM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});